### ISSUE TITLE
Instructions for contribution

### ISSUE THREAD

**Issue by AngryMaciek** [zavolanlab/SCUREL#3]
@dominikburri : consider adding a _CONTRIBUTING.md_ file with instructions for other developers?  
You can take a look at [this one](https://github.com/zavolanlab/bindz/blob/dev/CONTRIBUTING.md), for example. But you need to read it carefully and adapt to the specific project rules you'd like to set here.

**Comment by dominikburri** [comment]
added CONTRIBUTIONS.md with commit 9390ac380145f8f80674dac3f7ab4e13856f3e5a
